### ISSUE TITLE
一个菜单，只能绑定一次

### ISSUE THREAD

**Issue by yugi1017** [snokier/v-contextmenu#15]
我需要多个不同的元素，右键点开的菜单都一样，然后可以针对的实现关闭其他，关闭全部这样的功能

**Comment by XBT1** [comment]
### 一个 `ContextMenu` 可以被多个元素绑定

```html
<v-contextmenu ref="contextmenu">
  <v-contextmenu-item>菜单1</v-contextmenu-item>
</v-contextmenu>

<div id="box-1" v-contextmenu:contextmenu></div>
<div id="box-2" v-contextmenu:contextmenu></div>
```

### 可以关闭指定的 `ContextMenu`

`this.$refs.contextmenu.hide()`，参见 [VContextmenu](https://github.com/XBT1/v-contextmenu/blob/master/docs/usage.md#vcontextmenu) `hide` 方法

**Comment by yugi1017** [comment]
### 我试了如下代码
``` html
<v-contextmenu ref="contextmenu">
  <v-contextmenu-item>菜单1</v-contextmenu-item>
  <v-contextmenu-item>菜单2</v-contextmenu-item>
  <v-contextmenu-item>菜单3</v-contextmenu-item>
</v-contextmenu>
<div id='box-1' v-contextmenu:contextmenu>
  右键点击此区域
</div>
<div id='box-2' v-contextmenu:contextmenu>
  右键点击此区域2
</div>
```
页面效果是，右击第一个无效，右击第二个有效。

**Comment by XBT1** [comment]
暂时先写两个一样的 `contextmenu` 吧。这个功能会在稍后提供。

**Comment by yugi1017** [comment]
我是菜单需要这个功能，需要N个。。那我先处理其他的，回头再关注~

**Comment by XBT1** [comment]
`v2.3.0` 已支持
https://xbt1.github.io/v-contextmenu/#Multiple

**Comment by yugi1017** [comment]
多个组件可以触发了，但是如果是页面加载完以后，页面新的组件就触发不了这个右键功能了。
> 例子：菜单页签，页面初始化以后，默认页签可以，点击新模块，出现的新页签就不能触发这个右键功能了。

**Comment by XBT1** [comment]
能给个简单的代码例子吗？

**Comment by snokier** [comment]
inactive
