### ISSUE TITLE
当菜单里面有input输入框时,设置的autohide值为false时,有时候会失效,

### ISSUE THREAD

**Issue by zzymyjob** [snokier/v-contextmenu#24]

**Comment by zzymyjob** [comment]
![1](https://user-images.githubusercontent.com/32659451/38228149-735f556e-3734-11e8-8544-c14aba1d9db1.png)
如图,右键子菜单是iview里面的多选下拉框, 我设置了autohide为false, 但是多选时,会出现菜单栏消失 , 请问这个bug该怎么解决, 想了很久不知道该咋办, 非常感谢

**Comment by XBT1** [comment]
贴一下可复现的代码吧（简要一点）

**Comment by zzymyjob** [comment]
<v-contextmenu ref="contextmenu" @show="contextmenuShow">
			<v-contextmenu-submenu title="等下就删除的">
				<v-contextmenu-item :autoHide="false">
					<div>数值1</div>
				</v-contextmenu-item>
				<v-contextmenu-item :autoHide="false">
					<div>数值2</div>
				</v-contextmenu-item>
			</v-contextmenu-submenu>
	  </v-contextmenu>

你就数值1数值2来回点,多点几次,就会消失,按你的那个文档应该不会消失才对,

**Comment by zzymyjob** [comment]
(
<v-contextmenu ref="contextmenu" @show="contextmenuShow">
			<v-contextmenu-submenu title="等下就删除的">
				<v-contextmenu-item :autoHide="false">
					<div>数值1</div>
				</v-contextmenu-item>
				<v-contextmenu-item :autoHide="false">
					<div>数值2</div>
				</v-contextmenu-item>
			</v-contextmenu-submenu>
	  </v-contextmenu>
)

**Comment by XBT1** [comment]
我这里并没有复现（另外建议写成 `:auto-hide="false"`），你使用的操作系统和浏览器分别是？
我在 https://xbt1.github.io/v-contextmenu/#Submenu 里加了两个 `autoHide: false` 的菜单，帮忙测一下是否符合预期？

**Comment by snokier** [comment]
inactive
