### ISSUE TITLE
在IE11下，使用2.5.0版本提示错误，SCRIPT1003: 缺少 ':'

### ISSUE THREAD

**Issue by khty2000** [snokier/v-contextmenu#31]
在chrome下无问题，应该是es6的兼容性问题，修改了webpack配置，对v-contextmenu进行bable-loader处理，然后将import文件，由dist/index.common.js修改为src/index.js 后，ie11可以正常运行。

**Comment by JuGGnauT** [comment]
你好，请问您是怎么对v-contextmenu进行babel-loader处理啊。我处理了没有效果，任然报这个错

**Comment by lerit** [comment]
同样的问题，babel-loader一般忽略node_modules的，如果这个组件需要babel处理，请提供一下设置吧，谢谢

**Comment by snokier** [comment]
试一下 `v2.5.1`，修复了 babel 的问题

**Comment by JuGGnauT** [comment]
已经解决了 谢谢回复。

**Comment by zhangxb927** [comment]
怎么解决的啊，试了所有的方法都不行

**Comment by zhangxb927** [comment]
> 怎么解决的啊，试了所有的方法都不行

我终于解决了这个破问题，看了一大圈，代码完全没毛病，把安装包全删了，用npm去安装（之前用的cnpm），就不会报错了，气死了
