### ISSUE TITLE
怎么获取目标元素的绑定的data数据

### ISSUE THREAD

**Issue by caokun1021** [snokier/v-contextmenu#34]
想知道点击的目标元素，目标元素上有绑定的data数据，怎么获取

## 环境说明

- 组件版本：
- `Vue` 版本：2.0+
- 操作系统及版本：
- 浏览器及版本：

**Comment by snokier** [comment]
`VContextmenu` 上有个 `contextmenu` 事件，可参考 https://github.com/snokier/v-contextmenu/blob/master/docs/usage.md#vcontextmenu
该事件的参数为被点击元素的 `vnode`

**Comment by snokier** [comment]
`contextmenu` 事件示例可见：https://snokier.github.io/v-contextmenu/#Multiple
打开控制台可以看到 `vnode`
