### ISSUE TITLE
动态绑定class无效

### ISSUE THREAD

**Issue by taoer** [snokier/v-contextmenu#39]
<v-contextmenu-item  v-for="mergeType in mergeTypeList" :key="mergeType.index" @click="toggleMergeGroup(mergeType)">
      <i :class="{ 'el-icon-check': mergeStatus[mergeType]}"></i>合并{{mergeType}}
  </v-contextmenu-item>

**Comment by snokier** [comment]
请依照 issue 模板重新提 issue，并格式化代码，谢谢配合 ;)
