### ISSUE TITLE
v-contextmenu动态绑定ref

### ISSUE THREAD

**Issue by DarkRake** [snokier/v-contextmenu#42]
## 期望结果
指令动态绑定ref

## 实际结果
目前无法动态绑定ref菜单组件

## 复现步骤

我在循环内部使用您的菜单组件，但是遇到一个问题，指令试过过程中v-contextmenu:如何绑定动态值呢？

## 环境说明

- 组件版本：最新
- `Vue` 版本：2.5.2
- 操作系统及版本：mac os最新
- 浏览器及版本：谷歌最新

**Comment by snokier** [comment]
不支持例如 `v-contextmenu:xxx` 的动态绑定值。你可以让所有用到的元素公用一个 `Contextmenu`，动态渲染 `Contextmenu` 的内容。

**Comment by DarkRake** [comment]
好的，谢谢
